# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:concurrency: 5

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - default
  - mailers
  - payment
  - message
  - schedule

:schedule:
  schedule:
    every: <%= ENV.fetch('SCHEDULE_EVERY', "1d") %>
    class: ScheduleWorker
